services:
  hitl-refund:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: hitl-refund-agent

    ports:
      - "8501:8501"

    env_file:
      - .env

    environment:
      STORAGE_BACKEND: memory
      AUDIT_BACKEND: memory

    restart: unless-stopped
